"""Import selected factual action metadata, never guide prose or game textures.

The CSV snapshot is pinned. Output is committed, so builds and gameplay are offline.
Run after adding a reference sheet: python tools/import-actions.py
"""
import csv, hashlib, io, json, pathlib, re, urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
CACHE = ROOT / '.artifacts/import'
REV = 'd71de329cc6ed30c6fb16b9108cdf7d29c653302'
JOBS = {'Paladin':[19,1], 'Warrior':[21,3], 'DarkKnight':[32], 'Gunbreaker':[37],
        'Scholar':[28], 'Astrologian':[33], 'Sage':[40], 'Monk':[20,2], 'Dragoon':[22,4],
        'Ninja':[30,29], 'Samurai':[34], 'Reaper':[39], 'Viper':[41], 'Bard':[23,5],
        'Machinist':[31], 'Dancer':[38], 'Summoner':[27,26], 'RedMage':[35], 'Pictomancer':[42]}
# Multiple rows exist for TCJ / free enchanted variants: use the base PvE action icon.
CANONICAL = {'The Balance':37023,'Enchanted Riposte':7527,'Enchanted Zwerchhau':7528,'Enchanted Redoublement':7529,
             'Doton':2270,'Fuma Shuriken':2265,'Katon':2266,'Raiton':2267,'Suiton':2271,
             'Quadruple Technical Finish':16196}

def sheet(language):
    path=CACHE/f'Action-{REV}-{language}.csv'
    if not path.exists():
        CACHE.mkdir(parents=True,exist_ok=True)
        path.write_bytes(urllib.request.urlopen(f'https://raw.githubusercontent.com/xivapi/ffxiv-datamining/{REV}/csv/{language}/Action.csv',timeout=60).read())
    return {int(r['#']):r for r in csv.DictReader(io.StringIO(path.read_text(encoding='utf-8-sig')))}

en,fr=sheet('en'),sheet('fr')
eligible=[r for r in en.values() if r['IsPvP']=='False' and 0<int(r['ClassJobLevel'])<=100 and r['Name']]
records=[]
for path in sorted((ROOT/'src').glob('JobGuides*.cs')):
    text=path.read_text(encoding='utf8')
    for match in re.finditer(r' static void (\w+)\(Book b\)\{([\s\S]*?)(?=\n static void|\n}\s*$)',text):
        job,body=match.groups()
        if job not in JOBS: continue
        for name in sorted(set(re.findall(r'"([^"\n]*)"',body))):
            rows=[r for r in eligible if r['Name'].casefold()==name.casefold()]
            if not rows: continue  # French explanation rather than an action reference.
            own=[r for r in rows if int(r['ClassJob']) in JOBS[job]]
            rows=own or [r for r in rows if int(r['ClassJob']) in (0,-1)]
            if name in CANONICAL: rows=[r for r in rows if int(r['#'])==CANONICAL[name]]
            if len(rows)!=1: raise ValueError(f'Ambiguous action {job}/{name}: {[r["#"] for r in rows]}')
            r=rows[0];id=int(r['#'])
            records.append(dict(job=job,key=name,id=id,name=fr[id]['Name'],englishName=r['Name'],level=int(r['ClassJobLevel']),icon=int(r['Icon']),category=int(r['ActionCategory'])))

q=lambda s:json.dumps(s,ensure_ascii=False)
code=['// Generated by tools/import-actions.py; selected metadata from pinned XIVAPI CSV.',
      'namespace CycleOpener;', 'public static class JobActions {',
      ' static readonly Dictionary<(GuideJob,string),uint> Index=new(){']
for r in records: code.append(f'  [(GuideJob.{r["job"]},{q(r["key"].lower())})]={r["id"]}u,')
code+=[' };',' public static uint Id(GuideJob job,string name)=>Index[(job,name.ToLowerInvariant())];',
       ' public static IEnumerable<uint> For(GuideJob job)=>Index.Where(p=>p.Key.Item1==job).Select(p=>p.Value).Distinct();',
       ' public static void Register(Dictionary<uint,Spell> spells){']
unique={r['id']:r for r in records}
for id,r in sorted(unique.items()): code.append(f'  spells[{id}]=new({id},{q(r["name"])},{r["level"]},{r["icon"]},{q(r["englishName"])});')
code+=[' }','}']
(ROOT/'src/JobActions.cs').write_text('\n'.join(code)+'\n',encoding='utf8')
manifest=dict(revision=REV,url=f'https://github.com/xivapi/ffxiv-datamining/tree/{REV}',imported='2026-09-19',
              csvSha256={lang:hashlib.sha256((CACHE/f'Action-{REV}-{lang}.csv').read_bytes()).hexdigest() for lang in ('en','fr')},actions=records)
(ROOT/'docs/imported-actions.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(f'{len(records)} references, {len(unique)} unique action facts across {len(JOBS)} jobs; snapshot {REV}')
