namespace CycleOpener;

public sealed record ActionRequirement(string Badge,string Detail);

// Static prerequisites, not an availability check. No character state enters this table.
public static class Requirements {
 static readonly Dictionary<(GuideJob,uint),ActionRequirement> Rules=Build();
 static readonly ActionRequirement Beast=new("50 jauge","Consomme 50 de jauge de la bête.");
 static readonly ActionRequirement FreeBeast=new("50 jauge / gratuit","50 de jauge, ou une charge gratuite sous Relâchement bestial.");
 static readonly ActionRequirement Blood=new("50 Sang","Consomme 50 de Sang.");
 static readonly ActionRequirement FreeBlood=new("50 Sang / gratuit","50 de Sang, ou une charge gratuite sous Delirium de sang.");
 static readonly ActionRequirement Heat=new("50 Chaleur","Consomme 50 de Chaleur.");
 static readonly ActionRequirement FreeHeat=new("50 Chaleur / gratuit","50 de Chaleur, ou l’effet gratuit de Stabilisateur de canon.");
 static readonly ActionRequirement Palette=new("50 Palette","Consomme 50 de Palette.");
 static readonly ActionRequirement FreePalette=new("50 Palette / gratuit","50 de Palette, ou l’effet gratuit d’Imagi Ciel.");
 static readonly ActionRequirement DarkMana=new("3 000 PM","Consomme 3 000 PM ; la dépense gratuite devient possible après le déblocage de Nuit noir au niveau 70.");
 static readonly ActionRequirement Shroud=new("50 Linceul","Consomme 50 Linceul ; l’alternative gratuite arrive avec Récolte abondante au niveau 88.");
 static readonly ActionRequirement Mana20=new("20/20 ou gratuit","20 mana noire et 20 mana blanche, ou une charge gratuite de Manafication.");
 static readonly ActionRequirement Mana15=new("15/15 ou gratuit","15 de chaque mana, ou une charge gratuite de Manafication ; respecter le combo enchanté.");
 public static ActionRequirement? For(GuideContext state,uint id){
  if(Spells.Get(id).Level>state.Level)return null;
  var name=Spells.Get(id).EnglishName;
  if(state.Job==GuideJob.Warrior&&name is "Inner Beast" or "Steel Cyclone" or "Fell Cleave" or "Decimate")return state.Level>=70?FreeBeast:Beast;
  if(state.Job==GuideJob.DarkKnight&&name is "Bloodspiller" or "Quietus")return state.Level>=68?FreeBlood:Blood;
  if(state.Job==GuideJob.Machinist&&name=="Hypercharge")return state.Level>=66?FreeHeat:Heat;
  if(state.Job==GuideJob.Pictomancer&&name=="Subtractive Palette")return state.Level>=70?FreePalette:Palette;
  if(state.Job==GuideJob.DarkKnight&&state.Level<70&&name is "Flood of Darkness" or "Flood of Shadow" or "Edge of Darkness" or "Edge of Shadow")return DarkMana;
  if(state.Job==GuideJob.Reaper&&state.Level<88&&name=="Enshroud")return Shroud;
  if(state.Job==GuideJob.RedMage&&state.Level>=60){
   if(name is "Enchanted Riposte" or "Enchanted Moulinet")return Mana20;
   if(name is "Enchanted Zwerchhau" or "Enchanted Redoublement" or "Enchanted Moulinet Deux" or "Enchanted Moulinet Trois")return Mana15;
  }
  return Rules.GetValueOrDefault((state.Job,id));
 }
 static Dictionary<(GuideJob,uint),ActionRequirement> Build(){
  var result=new Dictionary<(GuideJob,uint),ActionRequirement>();
  void Add(GuideJob job,string badge,string detail,params string[] names){var rule=new ActionRequirement(badge,detail);foreach(var name in names)result.Add((job,JobActions.Id(job,name)),rule);}
  void Original(GuideJob job,string badge,string detail,params uint[] ids){var rule=new ActionRequirement(badge,detail);foreach(var id in ids)result.Add((job,id),rule);}
  var j=GuideJob.BlackMage;
  Original(j,"Électrifié","Nécessite l’effet Électrifié obtenu en changeant d’élément.",144,153,7447,7420,36986,36987);
  Original(j,"1 Polyglotte","Nécessite une charge de Polyglotte.",7422,16507);
  Original(j,"Feu astral","Nécessite le Feu astral ; entretenir sa durée avec les actions adaptées.",3577);
  Original(j,"Glace ombrale","Nécessite la Glace ombrale.",3576,16506);
  Original(j,"Feu + 800 PM","Nécessite le Feu astral et au moins 800 PM ; consomme les PM restants.",16505,162);
  Original(j,"6 Âmes astrales","Nécessite six charges d’Âme astrale obtenues avec les sorts de feu.",36989);
  Original(j,"Paradoxe prêt","Nécessite le marqueur Paradoxe après la transition élémentaire adéquate.",25797);
  j=GuideJob.WhiteMage;
  Original(j,"1 Lys","Nécessite un Lys disponible.",16531,16534);
  Original(j,"Lys de sang","Nécessite le Lys de sang nourri par trois sorts de Lys.",16535);
  Original(j,"Présence d’esprit","Nécessite une charge accordée par Présence d’esprit.",37009);
  Original(j,"Après Tempérance","Nécessite l’effet obtenu après Tempérance.",37011);
  j=GuideJob.Paladin;
  Add(j,"Proc Expiation","Nécessite l’effet accordé par Autorité royale.","Atonement");
  Add(j,"Après Expiation","Nécessite la suite accordée par Expiation.","Supplication");
  Add(j,"Après Supplication","Nécessite la suite accordée par Supplication.","Sepulchre");
  Add(j,"Combat acharné","Nécessite l’effet accordé par Combat acharné.","Goring Blade");
  Add(j,"Confiteor prêt","Nécessite l’effet de Requiescat / Imperator.","Confiteor");
  Add(j,"Combo magique","Nécessite le coup précédent de la chaîne commencée par Confiteor.","Blade of Faith","Blade of Truth","Blade of Valor");
  Add(j,"Après Vaillance","Nécessite la suite accordée par Lame de vaillance.","Blade of Honor");
  Add(j,"50 Serment","Consomme 50 de la jauge de Serment.","Sheltron","Holy Sheltron");
  j=GuideJob.Warrior;
  Add(j,"50 jauge + effet","50 de jauge et l’effet de Cri de guerre requis ; ces coups ne consomment pas les charges gratuites de Relâchement bestial.","Inner Chaos","Chaotic Cyclone");
  Add(j,"Relâchement bestial","Nécessite l’effet accordé par Relâchement bestial.","Primal Rend");
  Add(j,"Après Griffade","Nécessite la suite accordée par Griffade primitive.","Primal Ruination");
  Add(j,"3 coups gratuits","Nécessite les trois charges de courroux obtenues en consommant Relâchement bestial.","Primal Wrath");
  j=GuideJob.DarkKnight;
  Add(j,"3 000 PM / gratuit","3 000 PM, ou l’effet gratuit obtenu quand le bouclier Nuit noir se brise.","Flood of Darkness","Flood of Shadow","Edge of Darkness","Edge of Shadow");
  Add(j,"Delirium de sang","Nécessite une charge de Delirium de sang ; respecter l’ordre de la chaîne mono.","Scarlet Delirium","Comeuppance","Torcleaver","Impalement");
  Add(j,"Après Ombre","Nécessite l’effet accordé par Ombre vivante.","Disesteem");
  Add(j,"Terre salée active","Nécessite la zone de Terre salée active.","Salt and Darkness");
  Add(j,"3 000 PM","Consomme 3 000 PM.","The Blackest Night");
  j=GuideJob.Gunbreaker;
  Add(j,"1 cartouche","Nécessite une cartouche disponible.","Burst Strike","Fated Circle","Gnashing Fang");
  Add(j,"2 cartouches","Consomme deux cartouches.","Double Down");
  Add(j,"Combo Cartouche","Nécessite le coup précédent de la chaîne Croc pugnace.","Savage Claw","Wicked Talon");
  Add(j,"Proc Consécution","Nécessite la suite du coup précédent ; l’utiliser avant de la remplacer.","Jugular Rip","Abdomen Tear","Eye Gouge","Hypervelocity","Fated Brand");
  Add(j,"Sans pitié","Nécessite l’effet accordé par Sans pitié.","Sonic Break");
  Add(j,"Après Cartouches","Nécessite l’effet de Cartouches de sang puis les coups de la chaîne dans l’ordre.","Reign of Beasts","Noble Blood","Lion Heart");
  j=GuideJob.Scholar;
  Add(j,"1 Flux d’éther","Nécessite une charge de Flux d’éther.","Energy Drain","Lustrate");
  Add(j,"Après Stratagèmes","Nécessite l’effet de Stratagèmes entrelacés.","Baneful Impaction");
  Add(j,"Fée invoquée","Nécessite une fée invoquée.","Whispering Dawn");
  j=GuideJob.Astrologian;
  Add(j,"Carte piochée","Nécessite la carte correspondante obtenue par la pioche.","The Balance","Lord of Crowns");
  Add(j,"Après Divination","Nécessite l’effet accordé par Divination.","Oracle");
  Add(j,"Secte neutre","Nécessite l’effet accordé par Secte neutre.","Sun Sign");
  j=GuideJob.Sage;
  Add(j,"Eukrasia active","Activer Eukrasia pour transformer le sort ; ce n’est pas une aptitude à intercaler.","Eukrasian Dosis","Eukrasian Dosis II","Eukrasian Dosis III","Eukrasian Dyskrasia");
  Add(j,"1 Addersting","Nécessite une charge d’Addersting déjà disponible.","Toxikon","Toxikon II");
  Add(j,"1 Addersgall","Consomme une charge d’Addersgall.","Druochole","Kerachole");
  j=GuideJob.Monk;
  Add(j,"5 chakras","Nécessite cinq chakras ouverts.","Steel Peak","the Forbidden Chakra");
  Add(j,"3 formes identiques","Trois chakras de la même forme sous Équilibre parfait.","Elixir Field","Elixir Burst");
  Add(j,"3 formes différentes","Trois chakras de formes différentes sous Équilibre parfait.","Flint Strike","Rising Phoenix");
  Add(j,"2 Nadi + 3 chakras","Les deux Nadi ouverts et trois chakras de forme.","Tornado Kick","Phantom Rush");
  Add(j,"Énigme du feu","Nécessite l’effet accordé par Énigme du feu.","Fire's Reply");
  Add(j,"Énigme du vent","Nécessite l’effet accordé par Énigme du vent.","Wind's Reply");
  j=GuideJob.Dragoon;
  Add(j,"Vie du dragon","Nécessite la phase Vie du dragon et son effet associé.","Nastrond","Stardiver");
  Add(j,"2 charges","Nécessite deux charges de Regard du dragon.","Wyrmwind Thrust");
  Add(j,"Après Piqué","Nécessite la suite accordée par Piqué du dragon.","Rise of the Dragon");
  Add(j,"Après Plongeon","Nécessite la suite accordée par Plongeon céleste.","Starcross");
  j=GuideJob.Ninja;
  Add(j,"50 Ninki","Nécessite 50 Ninki.","Bhavacakra","Hellfrog Medium","Bunshin");
  Add(j,"Kassatsu + signes","Nécessite Kassatsu puis les signes indiqués dans la fiche.","Hyosho Ranryu","Goka Mekkyaku");
  Add(j,"Après Raiton","Nécessite le proc Raiju ; les coups normaux l’annulent.","Fleeting Raiju");
  Add(j,"Après Bunshin","Nécessite l’effet accordé par Bunshin.","Phantom Kamaitachi");
  Add(j,"Suiton actif","Nécessite l’effet de Suiton.","Meisui");
  Add(j,"Après Ten Chi Jin","Nécessite l’effet accordé par Ten Chi Jin.","Tenri Jindo");
  j=GuideJob.Samurai;
  Add(j,"1 Sen","Nécessite un Sen.","Higanbana");
  Add(j,"2 Sen","Nécessite deux Sen différents.","Tenka Goken");
  Add(j,"3 Sen","Nécessite trois Sen différents.","Midare Setsugekka");
  Add(j,"3 Sen + Tendo","Trois Sen et l’effet Tendo préparé par Meikyô Shisui.","Tendo Setsugekka");
  Add(j,"Après Iaijutsu","Nécessite le Iaijutsu correspondant et son effet de répétition.","Kaeshi: Goken","Kaeshi: Setsugekka","Tendo Kaeshi Setsugekka");
  Add(j,"25 Kenki","Consomme 25 Kenki.","Hissatsu: Shinten","Hissatsu: Kyuten");
  Add(j,"3 Méditations","Nécessite trois charges de Méditation.","Shoha");
  Add(j,"Après Ikishoten","Nécessite l’effet accordé par Ikishoten.","Ogi Namikiri");
  Add(j,"Après Ogi","Nécessite la suite après Ogi namikiri.","Kaeshi: Namikiri");
  Add(j,"50 Kenki + effet","50 Kenki et l’effet accordé par Ikishoten.","Zanshin");
  j=GuideJob.Reaper;
  Add(j,"50 Âme","Nécessite 50 Âme.","Blood Stalk","Grim Swathe","Gluttony");
  Add(j,"Faucheur d’âmes","Nécessite une charge de Faucheur d’âmes ; ne pas l’écraser.","Gibbet","Gallows","Guillotine");
  Add(j,"Proc Exécuteur","Nécessite une charge Exécuteur accordée par Gloutonnerie.","Executioner's Gibbet","Executioner's Gallows","Executioner's Guillotine");
  Add(j,"50 Linceul / gratuit","50 Linceul, ou l’effet gratuit de Récolte abondante si disponible.","Enshroud");
  Add(j,"Linceul actif","Nécessite la phase Linceul et une charge de Lémure.","Void Reaping","Cross Reaping","Grim Reaping","Communio");
  Add(j,"2 Lémures du néant","Nécessite deux charges de Lémure du néant.","Lemure's Slice","Lemure's Scythe");
  Add(j,"Effet de Linceul","Nécessite l’effet accordé à l’entrée en Linceul.","Sacrificium");
  Add(j,"Récolte + Communio","Nécessite Récolte abondante puis Communio sous son effet pour obtenir Perfectio prêt.","Perfectio");
  Add(j,"Cercle + délai","Nécessite l’offrande obtenue sous Cercle arcanique et la fin du délai de préparation.","Plentiful Harvest");
  j=GuideJob.Viper;
  Add(j,"1 anneau","Consomme un anneau ophidien.","Uncoiled Fury");
  Add(j,"50 Offrandes / effet","50 Offrandes ophidiennes ou l’effet gratuit de Communion ophidienne.","Reawaken");
  Add(j,"Éveil actif","Nécessite l’Éveil et l’hommage correspondant ; suivre les Générations dans l’ordre.","First Generation","Second Generation","Third Generation","Fourth Generation","Ouroboros");
  Add(j,"Suite du coup","Nécessite l’effet de l’attaque précédente ; utiliser la suite avant de la remplacer.","Twinfang Bite","Twinblood Bite","Twinfang Thresh","Twinblood Thresh","First Legacy","Second Legacy","Third Legacy","Fourth Legacy","Uncoiled Twinfang","Uncoiled Twinblood");
  j=GuideJob.Bard;
  Add(j,"Proc de tir","Nécessite le proc de tir correspondant ; sinon reprendre le tir de base.","Straight Shot","Refulgent Arrow","Wide Volley","Shadowbite");
  Add(j,"Menuet + charges","Nécessite le Menuet et au moins une charge de Répertoire ; privilégier trois charges.","Pitch Perfect");
  Add(j,"20 Âme minimum","20 jauge d’Âme minimum ; privilégier une jauge élevée et au moins 80 pour la suite dès son déblocage.","Apex Arrow");
  Add(j,"1 coda minimum","Nécessite au moins un coda ; trois après l’ouverture.","Radiant Finale");
  Add(j,"Après Barrage","Nécessite l’effet accordé par Barrage.","Resonant Arrow");
  Add(j,"Après Final radieux","Nécessite la suite accordée par Final radieux.","Radiant Encore");
  j=GuideJob.Machinist;
  Add(j,"Surchauffe","Nécessite la Surchauffe activée par Hypercharge.","Heat Blast","Blazing Shot","Auto Crossbow");
  Add(j,"50 Batterie min.","Nécessite au moins 50 Batterie.","Rook Autoturret","Automaton Queen");
  Add(j,"Après Scie","Nécessite l’effet accordé par Scie circulaire.","Excavator");
  Add(j,"Après Stabilisateur","Nécessite l’effet de Stabilisateur de canon.","Full Metal Field");
  j=GuideJob.Dancer;
  Add(j,"Proc de danse","Nécessite le proc correspondant ; sinon reprendre le combo de base.","Reverse Cascade","Fountainfall","Rising Windmill","Bloodshower");
  Add(j,"1 plume","Consomme une plume.","Fan Dance","Fan Dance II");
  Add(j,"Proc d’éventail","Nécessite le proc d’éventail correspondant.","Fan Dance III","Fan Dance IV");
  Add(j,"50 Esprit","Consomme 50 Esprit.","Saber Dance");
  Add(j,"50 Esprit + effet","50 Esprit et l’effet accordé par le Final technique.","Dance of the Dawn");
  Add(j,"2 pas réussis","Nécessite les deux pas corrects de la danse classique.","Double Standard Finish");
  Add(j,"4 pas réussis","Nécessite les quatre pas corrects de la danse technique.","Quadruple Technical Finish");
  Add(j,"Après Final technique","Nécessite l’effet accordé par le Final technique.","Tillana");
  Add(j,"Après Final classique","Nécessite l’effet de Final classique ou de Mouvement final.","Last Dance");
  Add(j,"Après Apothéose","Nécessite l’effet accordé par Apothéose.","Finishing Move");
  Add(j,"Tango endiablé","Nécessite l’effet accordé par Tango endiablé.","Starfall Dance");
  j=GuideJob.Summoner;
  Add(j,"Charge élémentaire","Nécessite les charges de l’invocation élémentaire active.","Gemshine","Precious Brilliance");
  Add(j,"1 Flux d’éther","Consomme une charge de Flux d’éther obtenue par l’aptitude de gain.","Fester","Necrotize","Painflare");
  Add(j,"Invocation active","Nécessite la transe ou le demi-invocation correspondant.","Astral Impulse","Astral Flare","Umbral Impulse","Umbral Flare","Deathflare","Sunflare","Enkindle Bahamut","Enkindle Solar Bahamut");
  Add(j,"Après Lumière","Nécessite l’effet accordé par Lumière brûlante.","Searing Flash");
  j=GuideJob.RedMage;
  Add(j,"20 / 20 mana","20 mana noire et 20 mana blanche.","Enchanted Riposte","Enchanted Moulinet");
  Add(j,"15 / 15 mana","15 de chaque mana ; respecter le combo enchanté.","Enchanted Zwerchhau","Enchanted Redoublement","Enchanted Moulinet Deux","Enchanted Moulinet Trois");
  Add(j,"Proc VerFeu","Nécessite le proc VerFeu.","Verfire");
  Add(j,"Proc VerTerre","Nécessite le proc VerTerre.","Verstone");
  Add(j,"3 gemmes","Nécessite trois gemmes de mana obtenues par la chaîne enchantée.","Verholy","Verflare");
  Add(j,"Combo de finisher","Nécessite le finisher précédent de la chaîne enchantée.","Scorch","Resolution");
  Add(j,"Après Enhardissement","Nécessite l’effet accordé par Enhardissement.","Vice of Thorns");
  Add(j,"Après Manafication","Nécessite l’effet obtenu en consommant les charges de Manafication.","Prefulgence");
  j=GuideJob.Pictomancer;
  Add(j,"Palette soustractive","Nécessite la palette soustractive et la teinte correspondant au coup dans la chaîne.","Blizzard in Cyan","Stone in Yellow","Thunder in Magenta","Blizzard II in Cyan","Stone II in Yellow","Thunder II in Magenta");
  Add(j,"1 Peinture blanche","Nécessite une charge de Peinture blanche.","Holy in White");
  Add(j,"Peinture + noir","Une charge de peinture et l’effet Peinture noire.","Comet in Black");
  Add(j,"Motif préparé","Nécessite le motif correspondant dessiné sur la toile.","Living Muse","Pom Muse","Steel Muse","Striking Muse","Starry Muse");
  Add(j,"Marteau actif","Nécessite les charges de marteau accordées par la muse d’arme ; respecter la chaîne.","Hammer Stamp","Hammer Brush","Polishing Hammer");
  Add(j,"Après Imagi Ciel","Nécessite l’effet accordé par Imagi Ciel.","Star Prism");
  return result;
 }
}
